### ISSUE TITLE
Constant int 23 on Entity.GetHashCode

### ISSUE THREAD

**Issue by felipe-allmeida** [NetDevPack/NetDevPack#2]
Hello!

Is it a good practice to use the number **23** on the bellow expression as a default on the Entity.cs? 

```C#
public override int GetHashCode()
{
    return (GetType().GetHashCode() ^ 93) + Id.GetHashCode();
}
```

Maybe I'm overreacting but magic numbers are prone to create errors. I suppose it would be better to leave that to the developer to choice the GetHashCode() implementation.

What do you think @EduardoPires ?

**Comment by EduardoPires** [comment]
It is necessary. There is a definition of code quality from Microsoft:
**CA2218**: Override GetHashCode on overriding Equals

https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2218
