### ISSUE TITLE
Upgrade solution to .Net Core 6

### ISSUE THREAD

**Issue by edward-teixeira** [NetDevPack/NetDevPack#37]
May we upgrade the solution from **netstandard2.1** to .Net Core 6?

![image](https://user-images.githubusercontent.com/45992962/184642861-b25778e2-e134-40ac-b5ba-90017ad45633.png)

**Comment by EduardoPires** [comment]
Using netstandard 2.1 we can maintain compatibility with all .NET versions. 

We can Add .NET 6 like that:

```xml
<TargetFrameworks>netstandard2.1;net5.0;net6.0</TargetFrameworks>
```
