### ISSUE TITLE
Question about GetHashCode

### ISSUE THREAD

**Issue by TeoDanilo** [NetDevPack/NetDevPack#6]
What is the reason for raising the hash's value? And why specifically to 93? Does it have a meaning or is it random?

At NetDevPack/Domain/Entity.cs
`return (GetType().GetHashCode() ^ 93) + Id.GetHashCode();`

**Comment by EduardoPires** [comment]
The hash value need to be a random number to avoid 'coincidences' during the multiply operation. The reason of 93 is personal :)
