### ISSUE TITLE
Tests failing due to DateTime.Date.Year

### ISSUE THREAD

**Issue by Allann** [NetDevPack/NetDevPack#8]
Since the MovieFactory is creating G movies in 2020, using DateTime.Date.Year now in 2021 causes the SpecValidation_Validate_ShouldReturnTrue test to fail.
Remove brittle tests by using a real value (i.e.  2020).

**Comment by EduardoPires** [comment]
Tks! I'll pay attention on this.

**Comment by brunohbrito** [comment]
Fixed at #10
